### ISSUE TITLE
Auto poweroff timer

### ISSUE THREAD

**Issue by vandisphotoo** [prokrypt/campsnap-fun#1]
Hi!

Have you reversed engineered the entire firmware? I'm looking for a way to disable the auto poweroff timer, or at least lengthen it to an hour or several hours.

Can you enlighten me or help me out?

Maarten

**Comment by prokrypt** [comment]
Hello there! Unfortunately I haven't reverse-engineered a single bit of the firmware (other than searching out images and audio) because I don't have the knowledge to do so. However, I did try to search for "600" (02 58) which would be the 10 minute default, and changed some of the more-likely-to-be-a-setting bits to "30" (00 1E), but my test failed...

**Comment by vandisphotoo** [comment]
Thanks for your quick reply!! Too bad, I'll contact Campsnap again if they can provide more functionality in their firmware :-)
